module.exports = { 'testcase': function(browser) { 
	browser.url("http://localhost:3000/workoutView")
	//.useCss()
	.click("#new-cycle")
	.setValue("#bodyWeight", "175")
	.click("#next")
	.click("#next")
	.setValue("#hangTimeOne", "20")
	.setValue("#hangTimeTwo", "20")
	.setValue("#hangTimeThree", "20")
	.click("#submit")
	.click("#start-set")
	.click("#max-effort")
	.click("#start-set")
	.click("#max-effort")
	.click("div.outer")
	.click("#start-set")
	.click("#max-effort")
	.click("#new-workout")
	.setValue("#bodyWeight", "175")
	.click("button.next")
	.click("#start-set")
	.click("#max-effort")
	.click("#start-set")
	.click("#max-effort")
	.click("#start-set")
	.click("#max-effort")
	.assert.containsText("#repMax1", "267.13")
	.end();
	}}